### ISSUE TITLE
Build time error

### ISSUE THREAD

**Issue by kaiosilveira** [raulpesilva/re-state#14]
Hi @raulpesilva, how is it going?

I've recently tried to perform a TS build of a web app I'm currently supporting for one of my clients, which was originally using `re-state@v1.1.19`, and I'm getting the following error:

```bash
my/project/root/node_modules/@raulpesilva/re-state/types/react/createReStateMethods.d.ts
TypeScript error in my/project/root/node_modules/@raulpesilva/re-state/types/react/createReStateMethods.d.ts(3,55):
'>' expected.  TS1005

    1 | import { SetReStateAction } from '../core';
    2 | import { DispatchReState } from './types';
  > 3 | declare type useReState<S extends string, V> = Record<`use${Capitalize<S>}`, () => [V, DispatchReState<SetReStateAction<V>>]>;
      |                                                       ^
    4 | declare type useReStateSelect<S extends string, V> = Record<`use${Capitalize<S>}Select`, () => V>;
    5 | declare type dispatchReState<S extends string, V> = Record<`dispatch${Capitalize<S>}`, DispatchReState<SetReStateAction<V>>>;
    6 | declare type getReState<S extends string, V> = Record<`get${Capitalize<S>}`, () => V>;


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried to update to [v1.2.32](https://www.npmjs.com/package/@raulpesilva/re-state/v/1.2.32), but the problem still persists.
There's [one entry in your changelog](https://github.com/raulpesilva/re-state/blob/master/CHANGELOG.md#1232---2022-09-07), thought, that says that a problem was fixed at `createReStateMethods`. Could it be related to my problem? 🤔 

I cloned the repo and poke around a little bit, but couldn't replicate the problem. Then I decided to open this issue.

Thanks in advance for your support on this matter.

**Comment by raulpesilva** [comment]
Hi @kaiosilveira all right and you?

🤔 I think it's because of the typescript version, for re-state versions from 1.2.30 onwards, typescript 4.1.5+ is required.
perhaps using pnpm to install dependencies should help resolve this.
Hope this can be helpful and thanks for the report

**Comment by kaiosilveira** [comment]
Oh, I see...

I tried your suggestion and it worked. It seems that my dep tree was broken. 🤦🏽 

Thank you for the support,

wish you a good Sunday ahead!
